name: sliders_sample
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  syncfusion_flutter_sliders: ^27.1.52
  syncfusion_flutter_charts: ^27.1.52

  cupertino_icons: '^1.0.8'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
