name: syncfusion_pdfviewer_platform_interface_example
description: Demonstrates how to use the syncfusion_pdfviewer_platform_interface plugin.
publish_to: 'none'

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  