name: maps_sample
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  syncfusion_flutter_maps:
    path: ../

  cupertino_icons: '>=0.1.3 <1.0.7'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/world_map.json
    - assets/australia.json
