
name: syncfusion_pdfviewer_windows
description: Windows platform implementation of the Flutter PDF Viewer library that lets you view the PDF documents seamlessly and efficiently.
version: 30.1.37
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_pdfviewer_windows

environment:
  sdk: ^3.7.0-0
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter



flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SyncfusionPdfviewerWindowsPlugin