
name: syncfusion_pdfviewer_macos
description: macOS platform implementation of the Flutter PDF Viewer library that lets you view the PDF documents seamlessly and efficiently.
version: 30.1.37
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_pdfviewer_macos

environment:
  sdk: ^3.7.0-0
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

  syncfusion_pdfviewer_platform_interface:
    path: ../syncfusion_flutter_pdfviewer_platform_interface
      
      



flutter:
  plugin:
    platforms:
     macos:
        pluginClass: SyncfusionFlutterPdfViewerPlugin