name: syncfusion_pdfviewer_web_example
description: Demonstrates how to use the syncfusion_pdfviewer_web with the help of syncfusion_flutter_pdfviewer plugin.
publish_to: 'none'

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
