name: localization_example
description: This project holds information about the usage of the syncfusion_localization package with the Flutter Syncfusion Calendar widget.
version: 1.0.0

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  syncfusion_localizations: ^29.2.7
  syncfusion_flutter_calendar: ^29.2.7
  cupertino_icons: '^1.0.8'

flutter:

  uses-material-design: true
