name: syncfusion_flutter_pdfviewer_example
description: Demonstrates how to use the syncfusion_flutter_pdfviewer plugin.
publish_to: 'none'

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
